module.exports = {
  logoImg:<img src={require('../assets/img/logo.png')} />,
  mobileIcon:<img src={require('../assets/img/mobile-icon.png')} />,
  pwdIcon:<img src={require('../assets/img/pwd-icon.png')} />,
  mainLogo:<img src={require('../assets/img/main-logo.png')} />,
  mainLogoSub:<img src={require('../assets/img/main-logo-sub.png')} />,
  avatar:<img src={require('../assets/img/avatar.png')} />,
  sub1:<i className="hgobox icon-zhuye"></i>,
  sub2:<i className="hgobox icon-pianqu"></i>,
  sub3:<i className="hgobox icon-shouhuogui"></i>,
  sub4:<i className="hgobox icon-shangpin"></i>,
  sub5:<i className="hgobox icon-guanggao"></i>,
  sub6:<i className="hgobox icon-jiankong"></i>,
  sub7:<i className="hgobox icon-yonghu"></i>,
  sub8:<i className="hgobox icon-baobiao"></i>,
  sub9:<i className="hgobox icon-caiwu"></i>,
  sub10:<i className="hgobox icon-jingxiaoshang"></i>,
  sub11:<i className="hgobox icon-xitongshezhi"></i>,
  sub12:<i className="hgobox icon-bangzhuzhongxin"></i>,
  indentIcon:<img src={require('../assets/img/indent-icon.png')} />,
  operator:['用户人员','工作人员','管理人员'],
  contractType:['全款合同','分期合同'],
  administrators:['否','是'],
  checked:["未审核","已审核"],
  enable:["未启用","已启用"],enable_show:['禁用','启用'],
  use:['未使用','已使用'],
  sex:['保密','男','女'],
  payType:['支付宝','微信','中国银行','中国农业银行','中国工商银行','中国建设银行','交通银行','中信银行','平安银行','中国光大银行','广发银行','恒丰银行','渤海银行','兴业银行','浙商银行','招商银行','上海浦东发展银行','中国民生银行','华夏银行'],
  premission:[{"c":"新增"},{"r":"读取"},{"u":"编辑"},{"d":"删除"},{"i":"导入"},{"e":"导出"},{"a":"分配"},{"v":"审核"},,{"n":"启用"},{"t":"转款"},{"l":"处理"},{"w":"提现"},{"p":"升级"}],
  dbr_worker:['默认','点位合伙人','配送人员'],
  cupboard_model:['百利','星星'],
  mcu_model:['无','mini','full','premium'],
  android_model:['无','IoT-3288A'],
  android_sdk:['无','5.1.1'],
  frequency:['无','安的高频-38400','罗丹贝尔超高频-115200'],
  assigned:['否','是'],
  has_camera:['否','是'],
  has_vi:['否','是'],
  bind:['否','是'],
  state_status1:['待入库','已入库','已出库','已售'],
  inventory_status1:['待操作','盘存成功','盘存失败'],
  goods_status1:['已入库','已出库','已售'],
  door1:['门异常','门开','门关'],
  lock1:['锁异常','锁开','锁关'],
  pay_type:['支付','退款'],
  bad_level:[{"-1":"无法评估该用户逾期状况"},{"0":"未命中逾期名单"},{"1":"命中一类名单"},{"2":"命中二类名单"},{"3":"命中三类名单"}],
  credited:['否','是'],
  publish_status1:['待发布','发布中','已发布'],
  order_id_status1:['待付款','交易成功','交易关闭'],
  app_status1:['待升级','升级中','已升级'],
  socketUrl:{
    pro:"wss://socketmanager.hgobox.com:12401",
    test:"wss://socketmanagertest.hgobox.com:12401"
  },
  androidDownload:{
    pro:"https://www.pgyer.com/R_distributor",
    test:"https://www.pgyer.com/fObD"
  }
}
